[features]
seeds = false
skip-lint = false
[programs.localnet]
quiz_programs = "2Ynn4VhKSE9h5kvD6hi4C7ZDmu1YYihGvopgdPpsgAgv"

[programs.devnet]
quiz_programs = "2Ynn4VhKSE9h5kvD6hi4C7ZDmu1YYihGvopgdPpsgAgv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/catrovacer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
